/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 brain-tank.glb -t
*/

import * as THREE from 'three'
import React, { forwardRef, useRef } from 'react'
import { MeshTransmissionMaterial, useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { Group } from 'three'

type GLTFResult = GLTF & {
  nodes: {
    Tank: THREE.Mesh
    Base: THREE.Mesh
    Top: THREE.Mesh
    BrainCerebrum: THREE.Mesh
    BrainStem: THREE.Mesh
    BrainCerebellum: THREE.Mesh
    Grate: THREE.Mesh
    StemPort: THREE.Mesh
    GrateTop: THREE.Mesh
    GrateTopCenter: THREE.Mesh
  }
  materials: {
    Glass: THREE.MeshStandardMaterial
    Metal: THREE.MeshStandardMaterial
    Brain: THREE.MeshStandardMaterial
  }
}

const background = new THREE.Color('white')

export const BrainTank = forwardRef<Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/brain-tank.glb') as GLTFResult
  return (
    <group {...props} ref={ref} dispose={null}>
      <mesh geometry={nodes.Tank.geometry}>
        <MeshTransmissionMaterial
          distortionScale={1}
          distortion={0.25}
          temporalDistortion={0.1}
          thickness={0.175}
          backside
          // backsideThickness={0.175}
          background={background}
          // roughness={0.1}
        />
      </mesh>
      <mesh geometry={nodes.Base.geometry} material={materials.Metal} />
      <mesh geometry={nodes.Top.geometry} material={materials.Metal} />
      <mesh geometry={nodes.BrainCerebrum.geometry} material={materials.Brain} />
      <mesh geometry={nodes.BrainStem.geometry} material={materials.Brain} />
      <mesh geometry={nodes.BrainCerebellum.geometry} material={materials.Brain} />
      <mesh geometry={nodes.Grate.geometry} material={materials.Metal} />
      <mesh geometry={nodes.StemPort.geometry} material={materials.Metal} />
      <mesh geometry={nodes.GrateTop.geometry} material={materials.Metal} position={[0, 1.612, 0]} />
      <mesh geometry={nodes.GrateTopCenter.geometry} material={materials.Metal} position={[0, 0.014, 0]} />
    </group>
  )
})
BrainTank.displayName = 'BrainTank'

useGLTF.preload('/brain-tank.glb')
